
INSERT INTO Cidades (nome, estadoId) VALUES('Abapa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Abatia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Acampamento das Minas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Acungui',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Adhemar de Barros',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Adrianopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Agostinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Agua Azul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Agua Boa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Agua Branca',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Agua do Boi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Agua Mineral',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Agua Vermelha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Agudos do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alecrim',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alexandra',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Almirante Tamandare',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Altamira do Parana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Altaneira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alto Alegre',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alto Alegre do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alto Amparo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alto do Amparo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alto Para',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alto Parana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alto Piquiri',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alto Pora',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alto Sabia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alto Santa Fe',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alto Sao Joao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Altonia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alvorada do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Alvorada do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Amapora',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Amorinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ampere',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Anahy',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Andira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Andorinhas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Angai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Angulo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Antas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Antonina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Antonio Brandao de Oliveira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Antonio Olinto',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Anunciacao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Aparecida do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Apiaba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Apucarana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Aquidaban',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Aranha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Arapongas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Arapoti',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Arapua',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Arapuan',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ararapira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Araruna',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Araucaria',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Areia Branca dos Assis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Areias',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Aricanduva',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ariranha do Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Aroeira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Arquimedes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Assai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Assis Chateaubriand',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Astorga',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Atalaia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Aurora do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bairro Cachoeira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bairro do Felisberto',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bairro Limoeiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Balsa Nova',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bandeirantes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bandeirantes D''oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Banhado',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barao de Lucena',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barbosa Ferraz',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barra Bonita',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barra do Jacare',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barra Grande',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barra Mansa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barra Santa Salete',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barracao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barras',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barreiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barreiro das Frutas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barreiros',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barrinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Barro Preto',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bateias',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Baulandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bela Vista',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bela Vista do Caroba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bela Vista do Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bela Vista do Paraiso',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bela Vista do Piquiri',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bela Vista do Tapiracui',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bentopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bernardelli',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Betaras',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bituruna',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Boa Esperanca',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Boa Esperanca do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Boa Ventura de Sao Roque',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Boa Vista',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Boa Vista da Aparecida',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bocaina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bocaiuva do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bom Jardim do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bom Jesus do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bom Progresso',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bom Retiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bom Sucesso',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bom Sucesso do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Borda do Campo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Borda do Campo de Sao Sebastiao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Borman',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Borrazopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Botuquara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bourbonia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Braganey',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bragantina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Brasilandia do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bugre',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Bulcao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cabrito',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cacatu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cachoeira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cachoeira de Cima',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cachoeira de Sao Jose',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cachoeira do Espirito Santo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cachoeirinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cadeadinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Caetano Mendes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cafeara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cafeeiros',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cafelandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cafezal do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Caita',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Caixa Prego',18);
INSERT INTO Cidades (nome, estadoId) VALUES('California',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Calogeras',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cambara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cambe',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cambiju',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cambira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campestrinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campina da Lagoa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campina do Miranguava',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campina do Simao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campina dos Furtados',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campina Grande do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campinas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campo Bonito',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campo do Meio',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campo do Tenente',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campo Largo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campo Largo da Roseira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campo Magro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Campo Mourao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Candido de Abreu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Candoi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Canela',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cantagalo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Canzianopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Capanema',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Capao Alto',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Capao Bonito',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Capao da Lagoa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Capao Grande',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Capao Rico',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Capitao Leonidas Marques',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Capivara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Capoeirinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cara Pintado',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cara-cara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Caraja',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Carambei',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Caramuru',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Caratuva',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Carazinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Carbonera',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Carlopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Casa Nova',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cascatinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cascavel',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Castro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Catanduvas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Catanduvas do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Catarinenses',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Caxambu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cedro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Centenario',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Centenario do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Central Lupion',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Centralito',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Centro Novo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cerne',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cerrado Grande',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cerro Azul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cerro Velho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ceu Azul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Chopinzinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cianorte',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cidade Gaucha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cintra Pimentel',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Clevelandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Coitinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colombo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Acioli',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Castelhanos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Castrolanda',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Centenario',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Cristina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Dom Carlos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Esperanca',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia General Carneiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Iapo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Melissa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Murici',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Padre Paulo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Pereira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Santos Andrade',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Sao Jose',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Sapucai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Saude',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colonia Tapera',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Colorado',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Comur',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Conceicao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Conchas Velhas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Conciolandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Congonhas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Congonhinhas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Conselheiro Mairinck',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Conselheiro Zacarias',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Contenda',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Copacabana do Norte',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Corbelia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cornelio Procopio',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Coronel Domingos Soares',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Coronel Firmino Martins',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Coronel Vivida',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Correia de Freitas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Corumbatai do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Corvo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Costeira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Covo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Coxilha Rica',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cristo Rei',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cruz Machado',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cruzeiro do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cruzeiro do Norte',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cruzeiro do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cruzeiro do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cruzmaltina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Cunhaporanga',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Curitiba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Curiuva',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Curucaca',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Deputado Jose Afonso',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Despique',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Despraiado',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Dez de Maio',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Diamante',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Diamante D''oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Diamante do Norte',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Diamante do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Doce Grande',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Dois Irmaos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Dois Marcos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Dois Vizinhos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Dom Rodrigo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Dorizon',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Douradina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Doutor Antonio Paranhos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Doutor Camargo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Doutor Ernesto',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Doutor Oliveira Castro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Doutor Ulysses',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Eduardo Xavier da Silva',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Emboguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Emboque',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Encantado D''oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Encruzilhada',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Eneas Marques',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Engenheiro Beltrao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Entre Rios',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Entre Rios do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Esperanca do Norte',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Esperanca Nova',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Espigao Alto do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Espirito Santo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Estacao General Lucio',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Estacao Roca Nova',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Europa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Euzebio de Oliveira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Faisqueira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Farol',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Faxina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Faxinal',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Faxinal do Ceu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Faxinal dos Elias',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Faxinal Santa Cruz',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fazenda do Brigadeiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fazenda dos Barbosas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fazenda Jangada',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fazenda Rio Grande',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fazenda Salmo Null',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fazendinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Felpudo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fenix',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fernandes Pinheiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fernao Dias',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ferraria',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ferreiras',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Figueira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Figueira do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fiusas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Flor da Serra',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Flor da Serra do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Florai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Floresta',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Florestopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Floriano',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Florida',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Floropolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fluviopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Formigone',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Formosa do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Foz do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Foz do Jordao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Francisco Alves',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Francisco Beltrao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Francisco Frederico Teixeira Guimaraes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Frei Timoteo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fueros',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Fundao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Gamadinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Gamela',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Gaucha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Gaviao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('General Carneiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('General Osorio',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Geremia Lunardelli',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Godoy Moreira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Goioere',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Goioxim',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Gois',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Goncalves Junior',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Graciosa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Grandes Rios',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guaipora',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guaira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guairaca',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guajuvira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guamiranga',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guamirim',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guapirama',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guapore',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guaporema',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guaraci',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guaragi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guaraituba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guarani',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guaraniacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guarapuava',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guarapuavinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guaraquecaba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guararema',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guaratuba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guarauna',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guaravera',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Guardamoria',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Harmonia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Herculandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Herval Grande',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Herveira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Hidreletrica Itaipu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Honorio Serpa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Iarama',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ibaiti',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ibema',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ibiaci',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ibipora',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Icara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Icaraima',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Icatu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Igrejinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Iguaracu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Iguatemi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Iguatu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Iguipora',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ilha do Mel',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ilha dos Valadares',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Imbau',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Imbauzinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Imbituva',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Inacio Martins',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Inaja',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Independencia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Indianopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Inspetor Carvalho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Invernada',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Invernadinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Iolopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ipiranga',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ipora',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Iracema do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Irapuan',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Irati',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Irere',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Iretama',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Itaguaje',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Itaiacoca',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Itaipulandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Itambaraca',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Itambe',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Itapanhacanga',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Itapara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Itapejara D''oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Itaperucu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Itaqui',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Itauna do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Itinga',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ivailandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ivaipora',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ivaitinga',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ivate',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ivatuba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jaborandi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jaboti',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jaboticabal',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jaburu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jacare',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jacarezinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jaciaba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jacutinga',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jaguapita',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jaguariaiva',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jandaia do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jangada',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jangada do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Janiopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Japira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Japura',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jaracatia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jardim',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jardim Alegre',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jardim Olinda',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jardim Paredao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jardim Paulista',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jardinopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jataizinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Javacae',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jesuitas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Joa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Joaquim Tavora',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jordaozinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jose Lacerda',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Juciara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jundiai do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Juranda',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Jussara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Juvinopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Kalore',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Km Null',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lagoa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lagoa Bonita',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lagoa dos Ribas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lagoa Dourada',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lagoa Seca',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lagoa Verde',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lagoinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lajeado',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lajeado Bonito',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lajeado Grande',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lambari',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lapa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Laranja Azeda',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Laranjal',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Laranjeiras do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lavra',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lavrinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Leopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lerroville',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lidianopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lindoeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Linha Giacomini',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Loanda',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lobato',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Londrina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lopei',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lovat',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Luar',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Luiziana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lunardelli',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Lupionopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Macaco',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Macucos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Maira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Maita',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mallet',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Malu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mambore',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mandacaia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mandaguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mandaguari',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mandiocaba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mandirituba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Manfrinopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mangueirinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Manoel Ribas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Maraba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Maracana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marajo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Maravilha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marcelino',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marcionopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marechal Candido Rondon',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Margarida',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Maria Helena',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Maria Luiza',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marialva',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mariental',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marilandia do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marilena',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marilu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mariluz',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marimbondo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Maringa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mariopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Maripa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Maristela',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mariza',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marmelandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marmeleiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marques de Abrantes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marquinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marrecas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Martins',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Marumbi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Matelandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Matinhos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mato Queimado',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mato Rico',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Maua da Serra',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Medianeira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Meia-lua',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Memoria',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mendeslandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mercedes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mirador',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Miranda',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Mirante do Piquiri',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Miraselva',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Missal',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Monjolinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Monte Real',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Moreira Sales',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Morretes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Morro Alto',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Morro Ingles',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Munhoz de Melo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Natingui',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nilza',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nordestina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nossa Senhora Aparecida',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nossa Senhora da Aparecida',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nossa Senhora da Candelaria',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nossa Senhora das Gracas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nossa Senhora de Lourdes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nossa Senhora do Carmo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Alianca do Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Altamira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova America da Colina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Amoreira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Aurora',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Bilac',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Brasilia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Brasilia do Itarare',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Cantu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Concordia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Esperanca',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Esperanca do Sudoeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Fatima',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Laranjeiras',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Londrina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Lourdes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Olimpia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Prata do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Riqueza',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Santa Barbara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Santa Rosa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Tebas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Tirol',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Nova Videira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Novo Horizonte',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Novo Itacolomi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Novo Jardim',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Novo Sarandi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Novo Sobradinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Novo Tres Passos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Olaria',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Olho Agudo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Olho D''agua',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Oroite',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ortigueira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ourilandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ourizona',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ouro Verde do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ouro Verde do Piquiri',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Padre Ponciano',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paicandu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paiol de Baixo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paiol Queimado',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paiquere',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Palmas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Palmeira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Palmeirinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Palmira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Palmital',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Palmital de Sao Silvestre',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Palmitopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Palotina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Panema',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pangare',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Papagaios Novos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paraiso do Norte',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Parana D''oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paranacity',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paranagi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paranagua',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paranapoema',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paranavai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Passa Una',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Passo da Ilha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Passo dos Pupos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Passo Fundo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Passo Liso',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pato Bragado',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pato Branco',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Patos Velhos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pau D''alho Do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paula Freitas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paulistania',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Paulo Frontin',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Peabiru',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pedra Branca do Araraquara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pedras',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pedro Lustosa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pelado',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Perobal',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Perola',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Perola do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Perola Independente',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Piassuguera',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pien',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pinare',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pinhais',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pinhal do Sao Bento',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pinhal Preto',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pinhalao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pinhalzinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pinhao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pinheiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Piquirivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Piracema',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pirai do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pirapo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Piraquara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Piriquitos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pitanga',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pitangueiras',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pitangui',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Planaltina do Parana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Planalto',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pocinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Poema',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ponta do Pasto',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ponta Grossa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pontal do Parana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porecatu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Portao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porteira Preta',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto Amazonas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto Barreiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto Belo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto Brasilio',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto Camargo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto de Cima',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto Meira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto Mendes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto Rico',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto San Juan',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto Santana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto Sao Carlos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto Sao Jose',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Porto Vitoria',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Prado Ferreira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pranchita',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Prata',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Prata Um',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Presidente Castelo Branco',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Presidente Kennedy',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Primeiro de Maio',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Progresso',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Prudentopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Pulinopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Quatigua',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Quatro Barras',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Quatro Pontes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Quebra Freio',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Quedas do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Queimados',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Querencia do Norte',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Quinta do Sol',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Quinzopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Quitandinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ramilandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rancho Alegre',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rancho Alegre D''oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Realeza',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Reboucas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Regiao dos Valos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Reianopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Renascenca',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Reserva',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Reserva do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Retiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Retiro Grande',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ribeirao Bonito',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ribeirao Claro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ribeirao do Pinhal',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ribeirao do Pinheiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Abaixo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Azul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Bom',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Bonito',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Bonito do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Branco do Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Branco do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Claro do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio da Prata',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio das Antas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio das Mortes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio das Pedras',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio das Pombas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio do Mato',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio do Salto',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Negro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Novo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Pinheiro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Quatorze',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Saltinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Saudade',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rio Verde',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Roberto Silveira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Roca Velha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rolandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Romeopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Roncador',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rondinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rondon',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Rosario do Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sabaudia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sagrada Familia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Salgado Filho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Salles de Oliveira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Saltinho do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Salto do Itarare',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Salto do Lontra',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Salto Portao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Samambaia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Amelia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Cecilia do Pavao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Clara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Cruz de Monte Castelo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Eliza',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Esmeralda',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Fe',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Fe do Pirapo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Helena',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Ines',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Isabel do Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Izabel do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Lucia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Lurdes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Luzia da Alvorada',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Margarida',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Maria',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Maria do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Maria do Rio do Peixe',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Mariana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Monica',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Quiteria',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Rita',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Rita do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Rosa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Tereza do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Terezinha de Itaipu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santa Zelia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santana do Itarare',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santo Antonio',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santo Antonio da Platina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santo Antonio do Caiua',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santo Antonio do Iratim',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santo Antonio do Palmital',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santo Antonio do Paraiso',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santo Antonio do Sudoeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santo Inacio',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Santo Rei',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Bento',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Braz',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Camilo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Carlos do Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Cirilo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Clemente',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Cristovao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Domingos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Francisco',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Francisco de Imbau',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Francisco de Sales',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Gabriel',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Gotardo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Jeronimo da Serra',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Joao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Joao D''oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Joao da Boa Vista',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Joao do Caiua',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Joao do Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Joao do Pinhal',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Joao do Triunfo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Joaquim',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Joaquim do Pontal',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Jorge D''oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Jorge do Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Jorge do Patrocinio',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Jose',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Jose da Boa Vista',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Jose das Palmeiras',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Jose do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Jose do Itavo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Jose do Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Jose dos Pinhais',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Judas Tadeu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Leonardo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Lourenco',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Luiz',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Luiz do Puruna',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Manoel do Parana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Marcos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Martinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Mateus do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Miguel',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Miguel do Cambui',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Miguel do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Paulo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Pedro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Pedro do Florido',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Pedro do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Pedro do Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Pedro do Parana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Pedro Lopei',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Pio X',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Roque',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Roque do Pinhal',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Salvador',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Sebastiao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Sebastiao da Amoreira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Silvestre',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Tome',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Valentim',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sao Vicente',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sape',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sapopema',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sarandi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Saudade do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sede Alvorada',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sede Chaparral',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sede Nova Sant''ana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sede Progresso',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Selva',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Senges',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Senhor Bom Jesus dos Gramados',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Serra dos Dourados',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Serra Negra',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Serranopolis do Iguacu',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Serraria Klas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Serrinha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sertaneja',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sertanopolis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sertaozinho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sete Saltos de Cima',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Silvolandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Siqueira Belo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Siqueira Campos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Socavao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Socorro',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sulina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sumare',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sussui',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Sutis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Taipa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tamarana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tambarutaca',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tamboara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tanque Grande',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tapejara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tapira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tapui',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Taquara',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Taquari dos Polacos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Taquari dos Russos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Taquaruna',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Teixeira Soares',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Telemaco Borba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Teolandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tereza Breda',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tereza Cristina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Terra Boa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Terra Nova',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Terra Rica',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Terra Roxa',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tibagi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tijucas do Sul',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tijuco Preto',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Timbu Velho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tindiquera',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tiradentes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Toledo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tomaz Coelho',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tomazina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tranqueira',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tres Barras do Parana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tres Bicos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tres Bocas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tres Capoes',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tres Corregos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tres Lagoas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tres Pinheiros',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tres Placas',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Triangulo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Trindade',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Triolandia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tronco',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tunas do Parana',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tuneiras do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tupassi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Tupinamba',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Turvo',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ubaldino Taques',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ubauna',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ubirata',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Umuarama',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Uniao',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Uniao da Vitoria',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Uniao do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Uniflor',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Urai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Usina',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Uvaia',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Valentins',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Valerio',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vargeado',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vassoural',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Ventania',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vera Cruz do Oeste',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vera Guarani',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vere',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vida Nova',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vidigal',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Alta',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Diniz',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila dos Roldos',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Florida',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Gandhi',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Guay',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Nova',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Nova de Florenca',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Paraiso',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Reis',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Rica do Ivai',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Roberto Brzezinski',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Silva Jardim',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vila Velha',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Virmond',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vista Alegre',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vista Bonita',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vitoria',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Vitorino',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Warta',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Wenceslau Braz',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Xambre',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Xaxim',18);
INSERT INTO Cidades (nome, estadoId) VALUES('Yolanda',18);
